import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';
import CircuitEditor from 'components/Pages/CircuitEditor';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Circuit</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* <header className={styles.header}>React Flow - Next.js Example</header> */}
			<CircuitEditor />
		</div>
	);
};

export default Home;
